version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      production-dependencies:
        applies-to: "version-updates"
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/ts"
    schedule:
      interval: "weekly"
    groups:
      production-dependencies:
        applies-to: "version-updates"
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/wasm/wasm/ts"
    schedule:
      interval: "weekly"
    groups:
      production-dependencies:
        applies-to: "version-updates"
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      ci-dependencies:
        applies-to: "version-updates"
        patterns:
          - "*"
  - package-ecosystem: "cargo"
    directory: "/wasm/tuningplayground"
    schedule:
      interval: "weekly"
    groups:
      rust-dependencies:
        applies-to: "version-updates"
        patterns:
          - "*"
  - package-ecosystem: "cargo"
    directory: "/wasm/tuningplayground/keymapping"
    schedule:
      interval: "weekly"
    groups:
      rust-dependencies:
        applies-to: "version-updates"
        patterns:
          - "*"
  - package-ecosystem: "cargo"
    directory: "/wasm/tuningplayground/tuning_systems"
    schedule:
      interval: "weekly"
    groups:
      rust-dependencies:
        applies-to: "version-updates"
        patterns:
          - "*"
  - package-ecosystem: "cargo"
    directory: "/wasm/textprocessing"
    schedule:
      interval: "weekly"
    groups:
      rust-dependencies:
        applies-to: "version-updates"
        patterns:
          - "*"
  - package-ecosystem: "cargo"
    directory: "/wasm/textprocessing/hangeul_conversion"
    schedule:
      interval: "weekly"
    groups:
      rust-dependencies:
        applies-to: "version-updates"
        patterns:
          - "*"
  - package-ecosystem: "cargo"
    directory: "/wasm/glsl2hlsl"
    schedule:
      interval: "weekly"
    groups:
      rust-dependencies:
        applies-to: "version-updates"
        patterns:
          - "*"
  - package-ecosystem: "cargo"
    directory: "/wasm/bundle"
    schedule:
      interval: "weekly"
    groups:
      rust-dependencies:
        applies-to: "version-updates"
        patterns:
          - "*"
