[package]
authors = ["hill <hill@hilll.dev>"]
description = "expose my rust libraries to wasm"
edition = "2024"
license = "AGPL-3.0"
name = "tuningplayground"
repository = "https://github.com/float3/tuningplayground"
version = "1.0.0"

[features]
default = ["wasm"]
wasm = ["dep:wasm-bindgen"]

[dependencies]
engrave = { workspace = true }
wasm-bindgen = { workspace = true, optional = true }
music21-rs = { workspace = true }
keymapping = { path = "./keymapping" }
js-sys = "0.3.104"
