[package]
name = "adventofcode"
version = "1.0.0"
edition = "2021"
authors = ["hill <hill@hilll.dev>"]
description = "adventofcode done in wasm"
license = "AGPL-3.0"
repository = "https://github.com/float3/float3.github.io"

[workspace]
members = ["hangeul_conversion"]

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["mini-alloc", "wasm"]
console_error_panic_hook = ["dep:console_error_panic_hook"]
mini-alloc = ["dep:mini-alloc"]
wasm = ["dep:wasm-bindgen"]

[dependencies]
bpmf_py = "0.1.0"
character_converter = "2.1.5"
chinese-number = "0.7.7"
console_error_panic_hook = { version = "0.1.7", optional = true }
hanja = "0.1.1"
japanese = "0.1.2"
japanese_number_converter = "0.1.0"
mini-alloc = { version = "0.6.0", optional = true }
pinyin = "0.10.0"
pinyin_zhuyin = "0.2.0"
roman = "0.1.6"
wasm-bindgen = { version = "0.2.99", optional = true }

[profile.release]
codegen-units = 1
debug = false
debug-assertions = false
incremental = true
lto = true
opt-level = 's'
overflow-checks = false
panic = "unwind"
rpath = false
split-debuginfo = "off"
strip = "symbols"

[package.metadata.wasm-pack.profile.release]
wasm-opt = ['-Os']

[package.metadata.wasm-pack.profile.release.wasm-bindgen]
debug-js-glue = false
demangle-name-section = false
dwarf-debug-info = false
omit-default-module-path = false
