//! Writes the transform cards into the bundle: their labels, the transform each
//! runs, the package that transform lives in, and the worked example already
//! run through it.
//!
//! Run by `site generate`. Needs every language feature on, since it renders the
//! whole table in one go; `site` builds it that way.

use std::fmt::Write as _;
use std::fs;
use std::path::PathBuf;

fn main() {
    let rendered = textprocessing::transforms::rendered().unwrap_or_else(|error| panic!("{error}"));

    let mut out = String::from(
        "// Generated by `site generate` (wasm/textprocessing/examples/generate_transforms.rs).\n\
         // Edit the table in wasm/textprocessing/src/transforms.rs, not this file.\n\n\
         export type Package = \"base\" | \"chinese\" | \"korean\"\n\n\
         export interface TransformCard {\n  \
           id: string\n  \
           group: string\n  \
           leftLabel: string\n  \
           rightLabel: string\n  \
           leftExample: string\n  \
           rightExample: string\n  \
           index: number\n  \
           reversible: boolean\n  \
           package: Package\n  \
           keywords: string[]\n\
         }\n\n\
         export const transformCards: TransformCard[] = [\n",
    );

    for rendered in &rendered {
        let card = rendered.card;
        let keywords = card
            .keywords
            .iter()
            .map(|keyword| string(keyword))
            .collect::<Vec<_>>()
            .join(", ");

        out.push_str("  {\n");
        for (key, value) in [
            ("id", string(card.id)),
            ("group", string(card.group)),
            ("leftLabel", string(card.left_label)),
            ("rightLabel", string(card.right_label)),
            ("leftExample", string(card.example)),
            ("rightExample", string(&rendered.right_example)),
            ("index", card.index.to_string()),
            ("reversible", rendered.reversible.to_string()),
            ("package", string(rendered.package.name())),
            ("keywords", format!("[{keywords}]")),
        ] {
            property(&mut out, key, &value);
        }
        out.push_str("  },\n");
    }
    out.push_str("]\n");

    let path =
        PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../ts/src/textprocessing/transforms.ts");
    fs::write(&path, out).expect("write transforms.ts");
    println!("wrote {} ({} cards)", path.display(), rendered.len());
}

/// The printed width prettier gives a line: two columns for each East Asian
/// wide character, one for anything else.
fn width(line: &str) -> usize {
    line.chars()
        .map(|ch| match u32::from(ch) {
            0x1100..=0x115F
            | 0x2E80..=0x303E
            | 0x3041..=0x33FF
            | 0x3400..=0x4DBF
            | 0x4E00..=0x9FFF
            | 0xA000..=0xA4CF
            | 0xAC00..=0xD7A3
            | 0xF900..=0xFAFF
            | 0xFE30..=0xFE4F
            | 0xFF00..=0xFF60
            | 0xFFE0..=0xFFE6
            | 0x1F300..=0x1F64F
            | 0x1F900..=0x1F9FF
            | 0x20000..=0x3FFFD => 2,
            _ => 1,
        })
        .sum()
}

/// One `key: value,` line of a card, broken the way prettier breaks one that
/// passes its 100-column limit: a string moves to a line of its own, and an
/// array puts each element on one.
fn property(out: &mut String, key: &str, value: &str) {
    let line = format!("    {key}: {value},");
    if width(&line) <= 100 {
        writeln!(out, "{line}").unwrap();
        return;
    }
    match value
        .strip_prefix('[')
        .and_then(|rest| rest.strip_suffix(']'))
    {
        Some(elements) => {
            writeln!(out, "    {key}: [").unwrap();
            for element in elements.split(", ") {
                writeln!(out, "      {element},").unwrap();
            }
            writeln!(out, "    ],").unwrap();
        }
        None => writeln!(out, "    {key}:\n      {value},").unwrap(),
    }
}

/// A TypeScript string literal quoted the way prettier would quote it: double
/// quotes unless the text holds more of those than of single quotes. Rust's
/// Debug for str escapes the way TypeScript reads a string and leaves printable
/// non-ASCII alone, so the table stays legible as the Chinese and Korean it is.
fn string(text: &str) -> String {
    let debug = format!("{text:?}");
    if text.matches('"').count() <= text.matches('\'').count() {
        return debug;
    }
    let inner = &debug[1..debug.len() - 1];
    format!("'{}'", inner.replace("\\\"", "\"").replace('\'', "\\'"))
}
