//! Writes the transform cards into the bundle: their labels, the transform each
//! runs, the package that transform lives in, and the worked example already
//! run through it.
//!
//! Run by `site generate`. Needs every language feature on, since it renders the
//! whole table in one go; `site` builds it that way.

use std::fmt::Write as _;
use std::fs;
use std::path::PathBuf;

fn main() {
    let rendered = textprocessing::transforms::rendered().unwrap_or_else(|error| panic!("{error}"));

    let mut out = String::from(
        "// Generated by `site generate` (wasm/textprocessing/examples/generate_transforms.rs).\n\
         // Edit the table in wasm/textprocessing/src/transforms.rs, not this file.\n\n\
         export type Package = \"base\" | \"chinese\" | \"korean\"\n\n\
         export interface TransformCard {\n  \
           id: string\n  \
           group: string\n  \
           leftLabel: string\n  \
           rightLabel: string\n  \
           leftExample: string\n  \
           rightExample: string\n  \
           index: number\n  \
           reversible: boolean\n  \
           package: Package\n  \
           keywords: string[]\n\
         }\n\n\
         export const transformCards: TransformCard[] = [\n",
    );

    for rendered in &rendered {
        let card = rendered.card;
        let keywords = card
            .keywords
            .iter()
            .map(|keyword| string(keyword))
            .collect::<Vec<_>>()
            .join(", ");

        out.push_str("  {\n");
        for (key, value) in [
            ("id", string(card.id)),
            ("group", string(card.group)),
            ("leftLabel", string(card.left_label)),
            ("rightLabel", string(card.right_label)),
            ("leftExample", string(card.example)),
            ("rightExample", string(&rendered.right_example)),
            ("index", card.index.to_string()),
            ("reversible", rendered.reversible.to_string()),
            ("package", string(rendered.package.name())),
            ("keywords", format!("[{keywords}]")),
        ] {
            writeln!(out, "    {key}: {value},").unwrap();
        }
        out.push_str("  },\n");
    }
    out.push_str("]\n");

    let path =
        PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../ts/src/textprocessing/transforms.ts");
    fs::write(&path, out).expect("write transforms.ts");
    println!("wrote {} ({} cards)", path.display(), rendered.len());
}

/// A TypeScript string literal quoted the way prettier would quote it: double
/// quotes unless the text holds more of those than of single quotes. Rust's
/// Debug for str escapes the way TypeScript reads a string and leaves printable
/// non-ASCII alone, so the table stays legible as the Chinese and Korean it is.
fn string(text: &str) -> String {
    let debug = format!("{text:?}");
    if text.matches('"').count() <= text.matches('\'').count() {
        return debug;
    }
    let inner = &debug[1..debug.len() - 1];
    format!("'{}'", inner.replace("\\\"", "\"").replace('\'', "\\'"))
}
