//! Writes the transform cards' worked examples into the bundle as plain text.
//!
//! Run by `site generate`. Needs every language feature on, since it renders the
//! whole table in one go; `site` builds it that way.

use std::fs;
use std::path::PathBuf;

fn main() {
    let rendered = textprocessing::examples::rendered();

    // A transform whose feature was compiled out returns its input untouched, so
    // an unchanged example means this was built wrong rather than that the answer
    // happens to equal the question. Nothing in the table is a fixed point.
    for (id, left, right) in &rendered {
        assert!(
            !right.is_empty(),
            "{id} rendered to nothing: the transform rejected its own example"
        );
        assert!(
            left != right,
            "{id} rendered to its own input: build this with all language features on"
        );
    }

    let mut out = String::from(
        "// Generated by `site generate` (wasm/textprocessing/examples/generate_examples.rs).\n\
         // Edit the table in wasm/textprocessing/src/examples.rs, not this file.\n\n\
         export const workedExamples: Record<string, string> = {\n",
    );

    // Rust's Debug for str quotes and escapes exactly the way TypeScript reads a
    // string literal, and leaves printable non-ASCII alone, so the table stays
    // legible as the Chinese and Korean it is.
    for (id, _left, right) in &rendered {
        out.push_str(&format!("  {}: {right:?},\n", key(id)));
    }
    out.push_str("}\n");

    let path =
        PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../ts/src/textprocessing/examples.ts");
    fs::write(&path, out).expect("write examples.ts");
    println!("wrote {} ({} examples)", path.display(), rendered.len());
}

/// Most ids are hyphenated and have to be quoted; the few that are plain words
/// must not be, or prettier rewrites the generated file and eslint fails.
fn key(id: &str) -> String {
    let identifier = !id.is_empty()
        && !id.starts_with(|c: char| c.is_ascii_digit())
        && id
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || c == '_' || c == '$');

    if identifier {
        id.to_string()
    } else {
        format!("{id:?}")
    }
}
