name: Generate

on:
  push:
    branches: [master]
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: generate-${{ github.ref }}
  cancel-in-progress: true

jobs:
  generate:
    if: ${{ github.actor != 'github-actions[bot]' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          submodules: recursive

      - name: Setup Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7
        with:
          python-version: "3.13"

      - name: Install Rust toolchain
        run: rustup toolchain install --profile minimal stable

      - name: Generate files
        run: cargo run --locked --no-default-features --manifest-path tools/site/Cargo.toml -- generate

      - name: Commit generated files
        run: cargo run --locked --no-default-features --manifest-path tools/site/Cargo.toml -- commit generate
