name: Deploy
on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "github-pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          token: ${{ secrets.TOKEN }}
          submodules: recursive

      - name: setup node
        uses: actions/setup-node@v4.1.0
        with:
          node-version: 22

      - name: dependencies
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs -o rustup.sh
          curl https://rustwasm.github.io/wasm-pack/installer/init.sh -ssf -o init.sh
          chmod +x rustup.sh init.sh
          ./rustup.sh --default-toolchain nightly --profile minimal -y
          rustup component add rustfmt clippy --toolchain nightly
          source "$HOME/.cargo/env"
          rm ~/.cargo/bin/rustfmt ~/.cargo/bin/rust-analyzer ~/.cargo/bin/cargo-fmt
          rustup update
          ./init.sh
          cargo install cargo-edit
          npm install -g pnpm

      - name: build
        run: |
          ./scripts/build.sh

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: "public"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.5
