on:
  push:
    branches:
      - master
      - dev
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "github-pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          token: ${{ secrets.TOKEN }}
          submodules: recursive

      - name: setup node
        uses: actions/setup-node@v4.1.0
        with:
          node-version: 20

      - name: python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: dependencies
        run: |
          cd tuningplayground
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs -o rustup.sh
          sh rustup.sh --default-toolchain nightly --profile minimal -y
          rustup component add rustfmt clippy --toolchain nightly
          source "$HOME/.cargo/env"
          rustup update
          curl https://rustwasm.github.io/wasm-pack/installer/init.sh -ssf | sh

          npm install -g pnpm

      - name: cache venv
        id: cache-venv
        uses: actions/cache@v4
        with:
          path: tuningplayground/music21-rs/venv
          key: ${{ runner.os }}-venv

      - name: cache pycache
        id: cache-pycache
        uses: actions/cache@v4
        with:
          path: tuningplayground/music21-rs/__pycache__
          key: ${{ runner.os }}-pycache

      - name: lint
        run: |
          sh ./update.sh

      - name: commit
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add -A
          git diff --staged --quiet || git commit -m "lint"
          git push || echo "No changes to commit"

      - name: build
        run: |
          sh ./build.sh

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: "public"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.5
