name: Update
on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "update_and_lint"
  cancel-in-progress: true

jobs:
  update_and_lint:
    if: ${{ github.actor != 'github-actions[bot]' && !contains(github.event.head_commit.message, 'update and lint') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          token: ${{ secrets.TOKEN }}
          submodules: recursive

      - name: setup node
        uses: actions/setup-node@v4.1.0
        with:
          node-version: 22

      - name: python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: dependencies
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs -o rustup.sh
          curl https://rustwasm.github.io/wasm-pack/installer/init.sh -ssf -o init.sh
          chmod +x rustup.sh init.sh
          ./rustup.sh --default-toolchain nightly --profile minimal -y
          rustup component add rustfmt clippy --toolchain nightly
          source "$HOME/.cargo/env"
          rm ~/.cargo/bin/rustfmt ~/.cargo/bin/rust-analyzer ~/.cargo/bin/cargo-fmt
          rustup update
          ./init.sh
          cargo install cargo-edit
          npm install -g pnpm

      - name: cache venv
        id: cache-venv
        uses: actions/cache@v4
        with:
          path: tuningplayground/music21-rs/venv
          key: ${{ runner.os }}-venv

      - name: cache pycache
        id: cache-pycache
        uses: actions/cache@v4
        with:
          path: tuningplayground/music21-rs/__pycache__
          key: ${{ runner.os }}-pycache

      - name: update and lint
        run: |
          ./scripts/update_and_lint.sh

      - name: commit
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add -A
          git pull
          git diff --staged --quiet || git commit -m "update and lint"
          git push || echo "No changes to commit"
